debug: false
clave: key
comandosCustom:
- money add {0} 10
readTimeOut: 5000
configVer: 3

command:
    global:
        cooldown: '&c&lERROR &8» &fEspera antes de volver a ejecutar este comando.'
        noPermission: '&c&lERROR &8» &fNo tienes permiso.'
        error: '&c&lERROR &8» &fHa ocurrido un error. Inténtalo de nuevo en unos minutos. Si el problema persiste, contacta con un administrador.'
        onlyPlayer: '&c&lERROR &8» &fEste comando solo puede ser ejecutado por un jugador.'
    vote:
        getting: '&a&lVOTE &8» &fObteniendo información...'
        notVoted: '&c&lVOTE &8» &fNo has votado hoy. Puedes hacerlo en &a{0}&f.'
        success: '&a&lVOTE &8» &fGracias por votar por el servidor.'
        successBroadcast: '&a&lVOTE &8» &a{0} &fha votado por el servidor usando &a/vote &fy ha obtenido una recompensa.'
        alreadyVoted: '&c&lERROR &8» &fYa has votado hoy.'
        error: '&c&lERROR &8» &fHa ocurrido un error al obtener la información de los votos. Intenta votar de nuevo en unas horas.'